diff --git a/Dockerfile b/Dockerfile
index 1ebe7a8..7ceb2ff 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -2,7 +2,7 @@
 #  cache sharing of the go mod download step.
 # Go cross compilation is also faster than emulation the go compilation across
 #  multiple platforms.
-FROM --platform=${BUILDPLATFORM} golang:1.16-buster AS builder
+FROM --platform=linux/s390x golang:1.16-buster AS builder
 
 # Copy sources
 WORKDIR $GOPATH/src/github.com/oauth2-proxy/oauth2-proxy
@@ -31,6 +31,7 @@ ARG BUILDPLATFORM
 RUN case ${TARGETPLATFORM} in \
          "linux/amd64")  GOARCH=amd64  ;; \
          "linux/arm64")  GOARCH=arm64  ;; \
+	 "linux/s390x")  GOARCH=s390x ;; \
          "linux/arm/v6") GOARCH=arm GOARM=6  ;; \
     esac && \
     printf "Building OAuth2 Proxy for arch ${GOARCH}\n" && \
